[target.x86_64-linux-android]
linker = "/opt/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang"
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"] 
ar = "/opt/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-Wl,--export-dynamic"]
[env]
CC_x86_64_linux_android = "/opt/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang"
CXX_x86_64_linux_android = "/opt/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang++"
AR_x86_64_linux_android = "/opt/android-sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"